name: ExpenseTracker
volumes:
  db:
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-app-db}
      - POSTGRES_USER=${DATABASE_USER:-user}
      - POSTGRES_PASSWORD=${DATABASE_PASS:-1234}
    restart: unless-stopped
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://user:1234@postgres/app-db}
    restart: unless-stopped
    depends_on:
      - postgres
