name: expense-tracker
volumes:
  db:
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-db}
      - POSTGRES_USER=${DATABASE_USER:-user}
      - POSTGRES_PASSWORD=${DATABASE_PASS:-1234}
    restart: unless-stopped
  app:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres
